### ISSUE TITLE
Squash 0.6 installation failure

### ISSUE THREAD

**Issue by Cyan4973** [quixdb/squash#109]
Trying to install squash 0.6 (release) onto a Linux Mint 17 configuration : 

````
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find Snappy (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Could NOT find Snappy (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Could NOT find Vala (missing:  VALA_EXECUTABLE) 
-- checking for modules 'glib-2.0;gobject-2.0'
--   package 'glib-2.0' not found
--   package 'gobject-2.0' not found
-- checking for modules 'glib-2.0;gobject-2.0'
--   package 'glib-2.0' not found
--   package 'gobject-2.0' not found
-- Configuring done
CMake Error at squash/CMakeLists.txt:38 (add_library):
  Cannot find source file:

    tinycthread/source/tinycthread.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
````

`bzip2` and `snappy` are both installed, but I guess it's not the problem.
`autogen` and `configure` went both fine, this message comes from `cmake .`

**Comment by nemequ** [comment]
Is this from the release or a git checkout?

**Comment by Cyan4973** [comment]
release

**Comment by nemequ** [comment]
Make sure you download https://github.com/quixdb/squash/releases/download/v0.6.0/squash-0.6.0.tar.bz2 not one of the archives github makes available.  They don't include submodules and there is no way to change that; I've complained about the issue in the past and their response was basically "we're aware of the issue".

**Comment by Cyan4973** [comment]
Yes, it works. Maybe it could be a good idea to indicate into release description that github automated packages do not work.

`cmake` generates roughly the same status message,but it nonetheless creates the `Makefile`, which then compiles fine.

````
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find Snappy (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Could NOT find Snappy (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Could NOT find Vala (missing:  VALA_EXECUTABLE) 
-- checking for modules 'glib-2.0;gobject-2.0'
--   package 'glib-2.0' not found
--   package 'gobject-2.0' not found
-- checking for modules 'glib-2.0;gobject-2.0'
--   package 'glib-2.0' not found
--   package 'gobject-2.0' not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yann/tmp/squash-0.6.0
````

**Comment by nemequ** [comment]
I'll add a check so that CMake generates a good error message.  I'll also grab a copy of Mint and see if I can figure out why bzip2 and snappy aren't found—I assume you have the dev packages (libbz2-dev and and libsnappy-dev) installed?

**Comment by Cyan4973** [comment]
Unfortunately, these 2 packages do not exist on Mint repository
