### ISSUE TITLE
bzip2 plugin doesn't support flushing

### ISSUE THREAD

**Issue by nemequ** [quixdb/squash#116]
The bzip2 plugin doesn't currently support flushing, but the library does.

**Comment by nemequ** [comment]
bzip2 seems to have a different definition of flushing.  If we call `BZ2_bzCompress(compressor, BZ_FLUSH)` until it returns `BZ_RUN_OK`, then call `BZ2_bzDecompress(decompressor)` with all the data from the compressor **not all the data is available** (in the `flush` unit test it will consistently provide 0 bytes of data).

Squash's definition of flushing is that all the decompressed content from up to the point of flushing will be immediately available from the decoder once the all the compressed (and flushed) data up to that point has been provided.

Closing this as invalid, but if someone can find a way to force the decoder to provide the output please reopen.

**Comment by terrelln** [comment]
FYI I've ran into the same issue with bzip2, and haven't found a way to solve it either.
