### ISSUE TITLE
Set up CI for OS X

### ISSUE THREAD

**Issue by nemequ** [quixdb/squash#128]
Squash should work on OS X.  It used to.  Unfortunately I don't have OS X, so until someone sets up CI for OS X it's hard to say whether or not it currently does.

Travis supports OS X, but last time I checked you had to choose between Linux and OS X, and there was no way for the two to coexist.  If that has changed we could just use Travis, if not the only other one I am aware of is [Hosted-CI](https://hosted-ci.com/plan/free).

Since I don't have OS X and know basically nothing about developing for it or with it, this is going to have to be done by someone else.

**Comment by nemequ** [comment]
It looks like Travis has improved here.  See [Testing Your Project on Multiple Operating Systems](http://docs.travis-ci.com/user/multi-os/).  And it should be possible to disable attempting to use gcc on OS X (if needed) by [excluding items from the build matrix](http://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix)

**Comment by nemequ** [comment]
9277de7aef047d76b04c377bc326a84e389058ee contains everything needed for this; just need to uncomment the osx line in `.travis.yml`.  Unfortunately there are some failures in the unit tests (lznt1 in the threads test, possibly others) which I need to resolve before enabling it.

**Comment by saprative** [comment]
@nemequ I want to test the code. But I am not accustomed with code base can you tell the exact process and give me some related doc

**Comment by nemequ** [comment]
@saprative https://github.com/quixdb/squash/blob/master/docs/building.md describes how to compile the library.  So, for OS X, if you don't already have homebrew installed you'll need to [install it](http://brew.sh/), then install the prerequisites (`brew install clang cmake ragel glib`).

Then you would just do whatever you would normally do for an autotools-based project (e.g., `./autogen.sh && make`, and possibly `make install`).  I'm not really familiar with OS X and homebrew, so I'm not sure if you need to pass a --prefix or --libdir argument to autogen.sh, but based on what I can find online it seems like you shouldn't; squash will install to /usr/local by default, which is right where homebrew wants it.  Once it's installed you should be able to use the [squash CLI](https://quixdb.github.io/squash/man/squash.1.html).

**Comment by nemequ** [comment]
Just to be clear, on OS X you'll want to use git.  I don't think 0.7 will even compile.

**Comment by saprative** [comment]
@nemequ I am using Xcode 7.0.1 . So what do you suggest .

**Comment by nemequ** [comment]
I have never used xcode (and don't have access to it) so I can't give you detailed instructions, but I know cmake has a generator for xcode project files.  You should be able to get some generic instructions for using cmake projects in xcode from Google.

**Comment by nemequ** [comment]
I have never used xcode (and don't have access to it) so I can't give you detailed instructions, but I know cmake has a generator for xcode project files.  You should be able to get some generic instructions for using cmake projects in xcode from Google.
