### ISSUE TITLE
zling plugin issue

### ISSUE THREAD

**Issue by jibsen** [quixdb/squash#153]
I finally managed to track down the issue that was making zling fail with MSVC but work elsewhere.

zling assumes it can check for EOF before attempting to read the next byte, whereas the squash zling codec does not set EOF until a read has been attempted.

This appears to work with GCC because zlings GetChar happens to return the last value of the uninitialized char that is used to store the read.

**Comment by nemequ** [comment]
Yuck.

I created a wip/issue-153 branch, could you see if that resolves the issue?

**Comment by jibsen** [comment]
It appears to work here, thanks. If you wish to test it yourself, you can initialize the value of `ch` to something other than 0 or 1:
```.patch
diff --git a/src/libzling_utils.cpp b/src/libzling_utils.cpp
index 4635f1d..5e722b4 100644
--- a/src/libzling_utils.cpp
+++ b/src/libzling_utils.cpp
@@ -38,7 +38,7 @@ namespace baidu {
 namespace zling {

 int Inputter::GetChar() {
-    unsigned char ch;
+    unsigned char ch = 42;
     GetData(&ch, 1);
     return ch;
 }
```

**Comment by nemequ** [comment]
Was this the only reason not to build the zling plugin on AppVeyor?

**Comment by jibsen** [comment]
No, there is richox/libzling#9 to get it to compile. This just fixes a bug.
