### ISSUE TITLE
Options without allow_zero still allow zero, if the range includes zero

### ISSUE THREAD

**Issue by Dr-Emann** [quixdb/squash#166]
The bad check is on [this line](https://github.com/quixdb/squash/blob/8250b835ba1eba587a52e3b7897999fad404182c/squash/options.c#L342). 

The following options have a range that includes 0, and allow_zero = false:
* bzip2: "work-factor"
* crush: "level"
* lz4f: "level" (defaults to 0, with allow_zero = false)
* lzham: "level"
* lzma: "lc", "lp" (defaults to 0), "pb", "mem-limit"
* lzma1: "lc", "lp" (defaults to 0), "pb"
* lzma2: "lc", "lp" (defaults to 0), "pb"
* pithy: "level"
* xz: "lc", "lp" (defaults to 0), "pb", "mem-limit"
* zling: "level" (defaults to 0)

**Comment by Dr-Emann** [comment]
I'm not sure if that's intended behavior or not.

**Comment by nemequ** [comment]
> I'm not sure if that's intended behavior or not.

Nope, allow_zero should be in addition to the range.  If 0 is included in the range it shouldn't matter if allow_zero is set or not.

Thanks for the report, I'll fix it ASAP.

**Comment by nemequ** [comment]
Should be fixed now, thanks!
