### ISSUE TITLE
Add more compilers to AppVeyor

### ISSUE THREAD

**Issue by nemequ** [quixdb/squash#186]
- [x] mingw
- [x] clang
- [x] clang-cl

For mingw, I think this is just a matter of adding a "MinGW Makefiles" generator to AppVeyor…

*Edited to change the bug from just mingw to several other compilers*

**Comment by nemequ** [comment]
> I think this is just a matter of adding a "MinGW Makefiles" generator to AppVeyor…

[Nope](https://ci.appveyor.com/project/quixdb/squash/build/323).

**Comment by jibsen** [comment]
I have a workaround for that in the [BriefLZ AppVeyor script](https://github.com/jibsen/brieflz/blob/master/appveyor.yml).

**Comment by jibsen** [comment]
I think we've got the following working on AppVeyor now:

  - Mingw-w64
  - Clang targeting mingw-w64
  - Clang targeting MSVC (clang-cl)

Still missing Clang/C2, but #185.
