### ISSUE TITLE
Feature : Act safely if no options are provided to var_args functions

### ISSUE THREAD

**Issue by elliotwoods** [quixdb/squash#188]
currently it can cause an access violation if you call function:

```c++
squash_codec_compress(this->squashCodec, &compressedSize, compressedData, uncompressedSize, uncompressedData);
```

rather than
```c++
squash_codec_compress(this->squashCodec, &compressedSize, compressedData, uncompressedSize, uncompressedData, NULL);
```

this is due to the empty arguments being interpreted as options, which are then processed and then we have a crash (in MSVC, i get an access violation on Debug but on Release it 'just works').

**Comment by Dr-Emann** [comment]
This is not possible in C. vararg functions do not know how many arguments they were passed, so there must be a sentinel value which designates the end of a list.

**Comment by nemequ** [comment]
Yep, @Dr-Emann is right.

On GCC we do use [the sentinel attribute](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-g_t_0040code_007bsentinel_007d-function-attribute-3234) to indicate that a `NULL` is required, but I'm not aware of any equivalent for MSVC.  If anyone is aware of something I'm willing to add it.

**Comment by nemequ** [comment]
FWIW, the sentinel attribute will work on clang and ICC, too.  Basically everywhere except MSVC.
