### ISSUE TITLE
[Documentation] Usage

### ISSUE THREAD

**Issue by umbreon222** [quixdb/squash#208]
Is there a possibility to get some documentation on setup, install, and usage?

**Comment by nemequ** [comment]
https://github.com/quixdb/squash/blob/master/docs/building.md and https://github.com/quixdb/squash/blob/master/docs/user-guide.md.  There are also some basic examples in the [examples/](https://github.com/quixdb/squash/tree/master/examples) directory.

Both documents are also available on the web site for 0.7.0 (see the documentation item in the menu, the user guide is part of the C API reference).  It's also possible to build the C API reference from git if you want; just install doxygen and `make doc` should work.

Is that sufficient, or did you have something else in mind?  I'm definitely open to any ideas for improving the documentation…

**Comment by umbreon222** [comment]
Ahh, I just figured those links would have been in the README.md. Thanks for the clarification. The documentation provided is definitely sufficient.
