### ISSUE TITLE
Adding lzfse benchmarks

### ISSUE THREAD

**Issue by jakirkham** [quixdb/squash#226]
It would be great if the benchmarks on the webpage could be updated to show lzfse performance. If they are already included, maybe a pointer about how to get them to show up would be nice. Thanks.

**Comment by nemequ** [comment]
LZFSE wasn't included in the last stable release of Squash, but it is in the unstable version:

https://quixdb.github.io/squash-benchmark/unstable/

**Comment by jakirkham** [comment]
They have since released a stable version. Would be curious to know how that affects the results.
