### ISSUE TITLE
Make use of all zstd compression levels?

### ISSUE THREAD

**Issue by bknowles** [quixdb/squash#229]
Looking at the chart at https://quixdb.github.io/squash-benchmark/#results-table I see only one entry for zstd, instead of a set of 22 levels as defined in the code.  All the other compression libraries seem to be tested at multiple compression levels, so I'm wondering why this one isn't?

**Comment by nemequ** [comment]
Squash 0.7 was released when zstd only offered a single level.  Future releases will include all levels; see [the unstable version of the benchmark](https://quixdb.github.io/squash-benchmark/unstable/) for an example.

**Comment by bknowles** [comment]
Sorry, I wasn't aware of the unstable version of the benchmark, which totally answers my question.

Thanks again!
