### ISSUE TITLE
Example doesn't show how to use squash_decompress with unknown decompressed length

### ISSUE THREAD

**Issue by wrosecrans** [quixdb/squash#242]
I may just be a bit thick, but the example at https://github.com/quixdb/squash/blob/master/examples/simple.c#L32 creates a char* to hold the full decompressed data.  In the example, it's doing a round trip of compressing and decompressing some data, so it known in advance exactly how big the result will be.  How should I figure out how much space I need to allocate to handle the decompressed data when it's not already known?

**Comment by jibsen** [comment]
For codecs that support it, I believe you can use `squash_codec_get_uncompressed_size`.

**Comment by nemequ** [comment]
Indeed.  And to determine whether a codec supports it you can use `(squash_codec_get_info(…) & SQUASH_CODEC_INFO_KNOWS_UNCOMPRESSED_SIZE)`
